apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-node-hpa
  # namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-node-deployment
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 5
status:
  currentCPUUtilizationPercentage: 0
  lastScaleTime: 
  currentReplicas: 1
  desiredReplicas: 1