apiVersion: v1
kind: Service
metadata:
  name: app-node-svc
spec:
  selector:
    app: my-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort